/**
 * Zola - Conversational Travel Assistant with Ubuntu
 * Professional, accurate assistance with warmth and humanity
 * Ubuntu: "I am because we are" - caring, community-focused, generous spirit
 */

export function getZolaResponse(userMessage) {
  const _lower = userMessage.toLowerCase();
  
  // Greetings & casual chat - Ubuntu warmth
  if (/^(hi|hello|hey|howdy|good morning|good afternoon|good evening|what's up|sup|sawubona|sanibonani)\b/i.test(userMessage)) {
    const greetings = [
      "Sawubona! 🤗 I'm Zola, and I'm here to help make your travel dreams come true. What adventure are you planning?",
      "Hello, my friend! It&apos;s wonderful to connect with you. I&apos;m Zola, your travel companion. Where shall we explore together?",
      "Hey there! 😊 I'm so happy you're here. I'm Zola, and I believe in making travel easy and joyful for everyone. How can I serve you today?",
      "Greetings! I&apos;m Zola - think of me as your travel family. Whatever you need, we&apos;ll figure it out together. What&apos;s on your mind?",
    ];
    return greetings[Math.floor(Math.random() * greetings.length)];
  }

  // About Zola / who are you - Ubuntu philosophy
  if (/who are you|what are you|tell me about yourself|your name/i.test(userMessage)) {
    return "I'm Zola! 💫 My name means 'calm' in Zulu, and that's what I'm here for - to bring peace to your travel planning. I believe in Ubuntu - 'I am because we are.' Your journey matters to me, your safety matters, your happiness matters. I'm not just here to book trips; I'm here to understand what you need and help you create beautiful memories. I know KwaZulu-Natal intimately, but I can guide you anywhere in the world. Think of me as family - what can I help you with today?";
  }

  // Services on the app - professional and comprehensive
  if (/what (can you do|do you offer|services)|how (does this|can you help)|features|help me/i.test(userMessage)) {
    return "I'm here to serve you with everything you need! 🌟 Here's what we can do together:\n\n✈️ **Flights** - Domestic & international, best prices, flexible dates\n🏨 **Accommodation** - Hotels, guesthouses, resorts, B&Bs - verified and safe\n🚐 **Shuttle & Transfers** - Airport pickups, intercity travel, 'Pick My Ride' feature\n🦁 **Tours & Activities** - Safaris, cultural experiences, adventure sports\n📦 **Complete Packages** - I'll bundle everything for better value\n🎉 **Events** - Concerts, festivals, sports, exhibitions\n💼 **Business Travel** - Corporate bookings, group arrangements\n\nI can also help with:\n• Travel advice and safety tips\n• Budget planning and cost estimates\n• Seasonal recommendations\n• Special requirements (accessibility, dietary, family needs)\n\nWhat matters most to you right now?";
  }

  // Destination recommendations - detailed and caring
  if (/where (should|can) (i|we) go|recommend (a )?destination|suggest (a )?place|best place/i.test(userMessage)) {
    if (/beach|coast|ocean|sea/i.test(userMessage)) {
      return "Ah, the coast! 🌊 Let me share some treasures with you:\n\n**Ballito** - Safe, family-friendly beaches with excellent restaurants. The tidal pools are perfect for little ones, and the Dolphin Coast lives up to its name!\n\n**Umhlanga** - Upscale and beautiful. Walk the promenade at sunset, enjoy world-class dining, and stay at hotels that truly care about service.\n\n**Salt Rock** - For those who love peace. Natural tidal pools, fewer crowds, and that authentic coastal feeling.\n\n**South Coast** (Margate, Ramsgate, Scottburgh) - Budget-friendly with warm waters and genuine hospitality. Great for extended families.\n\n**Sodwana Bay** - For divers and snorkelers - pristine waters, coral reefs, absolutely magical.\n\nWhat's important for you - family safety, romance, budget, or adventure?";
    }
    if (/safari|wildlife|game|animal/i.test(userMessage)) {
      return "Safari! 🦁 This is where my heart sings. Let me guide you properly:\n\n**Hluhluwe-iMfolozi Game Reserve**\n• Big Five (lion, leopard, rhino, elephant, buffalo)\n• World-renowned rhino conservation - you're supporting vital work\n• Day visits from R320/person or overnight in beautiful camps\n• Best time: May-September (dry season, animals at water)\n\n**iSimangaliso Wetland Park** (UNESCO site)\n• Hippos, crocs, incredible birdlife\n• Boat safaris on St Lucia estuary\n• Turtle nesting (Nov-Jan) - truly special\n\n**Phinda Private Game Reserve**\n• Luxury experience with expert guides\n• Low visitor numbers = intimate sightings\n• More investment, but unforgettable\n\nYour budget range? I'll match you with the perfect experience, and I only recommend ethical, conservation-focused operators.";
    }
    if (/mountain|hike|drakensberg|berg/i.test(userMessage)) {
      return "The uKhahlamba-Drakensberg! ⛰️ Our Dragon Mountains - a UNESCO World Heritage Site:\n\n**Cathedral Peak**\n• Accessible hiking trails for all fitness levels\n• Ancient San rock art (40,000+ years of human history)\n• Crystal-clear mountain streams\n• Best: Apr-May, Sep-Oct (mild weather)\n\n**Royal Natal National Park**\n• The Amphitheatre - one of Earth's great natural wonders\n• Tugela Falls (world's 2nd highest)\n• Photography opportunities that will take your breath away\n\n**Sani Pass**\n• 4x4 adventure to Lesotho border (2,874m altitude)\n• Visit a traditional Basotho village\n• Highest pub in Africa! ☕\n• Winter: Snow possible, check road conditions\n\nYour fitness level and interests? I'll tailor the perfect mountain experience for you.";
    }
    return "So many beautiful places to share with you! 🌍 Tell me what speaks to your soul:\n\n🏖️ Beach & Ocean - relaxation, water sports, sunset walks?\n🦒 Wildlife & Safari - connecting with nature, conservation?\n⛰️ Mountains & Hiking - fresh air, challenge, stunning views?\n🎭 Culture & Heritage - Zulu traditions, history, art?\n🌃 City Life - Durban's vibrancy, food, nightlife?\n🍷 Food & Wine - Midlands Meander, culinary experiences?\n\nEvery journey is unique, and I want to understand yours. What calls to you?";
  }

  // Budget & pricing - honest and helpful
  if (/how much|cost|price|budget|afford|cheap|expensive|what.*pay/i.test(userMessage)) {
    if (/durban|umhlanga|ballito/i.test(userMessage)) {
      return "Let me give you honest, accurate pricing for Durban/KZN (as of Nov 2025):\n\n**ACCOMMODATION** (per night)\n💰 Budget: R650-1,200 (backpackers, guesthouses, 3-star)\n💎 Mid-range: R1,500-2,800 (4-star hotels, good locations)\n✨ Luxury: R3,000-8,000+ (5-star, beachfront, premium service)\n\n**TRANSPORT**\n🚗 King Shaka Airport → Durban City: R250-400\n🚗 King Shaka → Umhlanga: R180-300\n🚗 Durban → Port Shepstone: R750-1,100\n🚕 Daily car rental: R350-650 (compact), R600-1,200 (SUV)\n\n**ACTIVITIES**\n🎯 uShaka Marine World: R195 (adult), R145 (child)\n🦁 Hluhluwe day safari: R320 entry + R450-800 guided drive\n🎭 Cultural tour: R450-850/person\n🍽️ Good restaurant meal: R150-350/person\n\n**REALISTIC DAILY BUDGETS**\n• Backpacker: R800-1,500/day (hostel, local transport, budget meals)\n• Mid-range: R2,500-4,500/day (3-4★ hotel, car rental, nice meals)\n• Luxury: R6,000+/day (5★ accommodation, guided experiences, fine dining)\n\nWhat's your comfortable budget? I'll create maximum value for you.";
    }
    return "I appreciate that budget matters - it shows wisdom! 💰 Let me be straight with you:\n\n**WEEKEND GETAWAYS** (2 nights)\n• Budget-friendly: R2,500-4,000/person (guesthouse, self-drive)\n• Comfortable: R5,000-8,000/person (good hotel, some meals included)\n• Luxury: R12,000+/person (5-star, all-inclusive)\n\n**WEEK-LONG TRIPS**\n• Self-catering beach: R8,000-15,000/person\n• Safari package: R15,000-35,000/person (depends on reserve)\n• International (Mauritius/Zanzibar): R18,000-45,000/person\n\n**MONEY-SAVING TIPS I ALWAYS SHARE:**\n✅ Book 6-8 weeks ahead for better rates\n✅ Midweek travel is 20-30% cheaper\n✅ Package deals save you 15-25% vs booking separately\n✅ April-May & Sep-Oct are 'shoulder season' - lower prices, great weather\n\nWhat's your budget range? I'll make every rand work hard for you, and I'll be upfront about all costs - no surprises.";
  }

  // Best time to visit - detailed and accurate
  if (/when (should|to|is best)|best time|season|weather|climate/i.test(userMessage)) {
    return "Timing is everything! Let me share what I know from years of experience: 🌤️\n\n**SUMMER (December-February)**\n☀️ Hot & humid (25-32°C)\n🌧️ Afternoon thunderstorms (but warm rain!)\n✅ Perfect for: Beach holidays, ocean swimming\n❌ Avoid for: Safaris (thick bush, animals dispersed)\n💡 Tip: Book accommodation early (peak season)\n\n**AUTUMN (March-May)**\n🍂 Mild & pleasant (18-26°C)\n☀️ Less rain, clear skies\n✅ BEST FOR: Everything! Hiking, sightseeing, comfortable travel\n🎯 April-May = My top pick for most trips\n💰 Shoulder season = Better prices\n\n**WINTER (June-August)**\n🌡️ Cooler & dry (12-23°C)\n☀️ Sunny days, crisp mornings\n✅ ABSOLUTE BEST for: Safari (animals at waterholes, thin bush, perfect visibility)\n🏖️ Still beach-friendly (ocean warm year-round)\n⛰️ Drakensberg can get snow (beautiful but check access)\n\n**SPRING (September-November)**\n🌺 Warming up (18-28°C)\n🌸 Wildflowers bloom\n✅ Great for: Hiking, outdoor activities, whale watching (Jun-Nov)\n🐋 Sardine Run (June-July) - spectacular!\n\n**MY HONEST RECOMMENDATIONS:**\n• Beach holiday → Dec-Feb or Apr-May\n• Safari → June-August (dry winter)\n• Budget-conscious → Apr-May or Sep-Oct\n• Avoid → December school holidays (crowded, expensive)\n\nWhen are you thinking of traveling? I'll tell you exactly what to expect.";
  }

  // Shuttles & transfers - professional and reassuring
  if (/shuttle|transfer|airport|pickup|transport|taxi|uber|ride/i.test(userMessage)) {
    return "Transport is so important for a stress-free trip! 🚗 Let me explain how we take care of you:\n\n**OUR 'PICK MY RIDE' SERVICE** 🌟\nYou choose your ride based on:\n\n✅ **Driver Ratings & Reviews**\n• All drivers are verified and rated\n• You see their experience, languages spoken, specialties\n• Real reviews from real travelers\n\n✅ **Vehicle Type**\n• Sedan (1-4 passengers)\n• SUV/Kombi (5-7 passengers)\n• Luxury vehicles available\n• All are clean, air-conditioned, insured\n\n✅ **Price Transparency**\n• See all options from budget to premium\n• No hidden fees - what you see is what you pay\n• Compare: Uber-style, traditional taxis, premium services\n\n✅ **Safety First**\n• All drivers background-checked\n• Live GPS tracking\n• 24/7 support if you need anything\n\n**POPULAR ROUTES (accurate pricing):**\n• King Shaka Airport → Durban: R250-400\n• King Shaka → Umhlanga: R180-300  \n• Durban → Port Shepstone: R750-1,100\n• Durban → Ballito: R350-550\n\nWhere do you need to go? Give me pickup point, destination, date, and number of passengers - I'll get you exact quotes from multiple drivers right now!";
  }

  // Accommodation - caring and detailed
  if (/hotel|accommodation|stay|lodging|guesthouse|resort|where to stay|place to sleep/i.test(userMessage)) {
    return "Finding the right place to stay is so important - it's your home away from home! 🏨 Let me help you properly:\n\n**I NEED TO UNDERSTAND YOUR NEEDS:**\n📍 **Destination?** (which city/area?)\n📅 **Dates?** (check-in & check-out)\n👥 **Guests?** (adults/children/rooms needed)\n💰 **Budget per night?**\n⭐ **Preferences?**\n\n**ACCOMMODATION TYPES WE OFFER:**\n\n🏨 **Hotels** (3-5 star)\n• Daily housekeeping, restaurants on-site\n• Good for: Convenience, business travel, families\n\n🏡 **Guesthouses & B&Bs**\n• Personal touch, home-cooked breakfasts\n• Good for: Authentic experience, meeting locals\n\n🏖️ **Resorts**\n• All-inclusive options, pools, entertainment\n• Good for: Relaxation, families, hassle-free holidays\n\n🌴 **Lodges** (safari/eco-lodges)\n• Unique locations, nature experiences\n• Good for: Safari, romance, special occasions\n\n🏠 **Self-catering**\n• Full kitchen, more space, privacy\n• Good for: Families, longer stays, budget-conscious\n\n**I ONLY RECOMMEND PLACES THAT:**\n✅ Are in safe areas\n✅ Have verified reviews\n✅ Meet cleanliness standards\n✅ Respond quickly to guests\n✅ Treat people with Ubuntu\n\nTell me your details, and I'll find you the perfect place - not just the cheapest, but the RIGHT fit for you.";
  }

  // Activities & things to do - enthusiastic and helpful
  if (/what to do|things to do|activities|fun|experience|adventure|bored/i.test(userMessage)) {
    return "So much to experience - life is meant to be lived! 🎉 Let me share what's truly worth your time:\n\n**WATER & BEACH** 🌊\n• Surfing lessons (Durban beaches) - R350-500\n• Snorkeling/diving (Sodwana, Aliwal Shoal)\n• Whale watching (Jun-Nov, Ballito) - R450-750\n• Kayaking with dolphins - unforgettable!\n\n**WILDLIFE & NATURE** 🦁\n• Game drives (Hluhluwe, iMfolozi)\n• Hippo & croc boat safaris (St Lucia)\n• Bird watching (500+ species in KZN!)\n• Turtle tours (Nov-Feb, iSimangaliso)\n\n**CULTURE & HERITAGE** 🎭\n• Zulu cultural villages (authentic experiences)\n• Shakaland - learn about King Shaka\n• Craft markets (Victoria Street, Esikhaleni)\n• Durban Indian heritage walking tour\n\n**ADVENTURE SPORTS** ⛰️\n• Hiking (Drakensberg trails - all levels)\n• Ziplining (Karkloof Canopy Tours)\n• Abseiling (Moses Mabhida Stadium)\n• Mountain biking (numerous trails)\n\n**FOOD & DRINK** 🍷\n• Durban curry cooking class\n• Midlands Meander food & craft route\n• Wine tasting (surprising KZN wines!)\n• Bunny chow tour (Durban's iconic dish)\n\n**RELAXATION** 💆\n• Beach walks & sunset picnics\n• Spa days (many excellent spas)\n• Botanical gardens (Durban has Africa's oldest!)\n\nWhat type of experiences make YOU feel alive? I'll create the perfect itinerary.";
  }

  // Packages & deals - value-focused
  if (/package|deal|special|combo|all.?inclusive|value/i.test(userMessage)) {
    return "I love packages - they give you the best value and peace of mind! 💎 Here's what I can put together for you:\n\n**WEEKEND ESCAPES** (2-3 nights)\n🏖️ Beach Break: R2,800-5,500/person\n• Accommodation (guesthouse/3-4★ hotel)\n• Breakfast daily\n• 1 activity or spa treatment\n• Airport transfer\n\n**SAFARI PACKAGES** (3-4 nights)\n🦁 Classic Safari: R12,000-18,000/person\n• Big Five game reserve accommodation\n• All meals included\n• 2 game drives daily\n• Expert guides\n• Conservation fees\n\n**BEACH & SAFARI COMBO** (5-7 nights)\n🌴🦁 Best of Both: R18,000-35,000/person\n• 3 nights safari + 3 nights beach\n• All transfers between locations\n• Specified meals\n• Selected activities\n\n**FAMILY PACKAGES**\n👨‍👩‍👧‍👦 Family Fun: From R15,000 (family of 4)\n• Kid-friendly accommodation\n• Family activities included\n• Flexible itinerary\n• Child discounts applied\n\n**INTERNATIONAL GETAWAYS**\n✈️ Mozambique: R8,500-25,000/person\n✈️ Mauritius: R18,000-45,000/person\n✈️ Zanzibar: R15,000-38,000/person\n(Includes flights, accommodation, transfers)\n\n**WHY PACKAGES SAVE MONEY:**\n💰 15-25% cheaper than booking separately\n💰 No surprise costs - you know total upfront\n💰 I negotiate better rates with our partners\n💰 Flexibility - I can adjust to your budget\n\n**CURRENT SPECIAL:**\n🎁 Book 3+ nights: Get airport transfer FREE\n🎁 Group of 4+: Additional 10% off\n\nWhat's your dream trip? Budget? Number of people? Let me build something special for you!";
  }

  // Events - detailed and current
  if (/event|concert|festival|show|exhibition|live music|performance/i.test(userMessage)) {
    return "Events bring so much joy! 🎉 We partner with Ticketmaster and other providers to bring you:\n\n**MUSIC & CONCERTS** 🎵\n• International artists (Moses Mabhida Stadium, Durban ICC)\n• Local talent (People's Park, Wilson's Wharf)\n• Jazz festivals (various venues)\n• Electronic music events\n\n**CULTURAL FESTIVALS** 🎭\n• Durban July (July) - Africa's greatest horse race & fashion event\n• Essence Festival (various dates)\n• Poetry Africa (October)\n• Time of the Writer Festival\n\n**SPORTING EVENTS** ⚽\n• Sharks rugby (Kings Park Stadium)\n• AmaZulu FC soccer  \n• Comrades Marathon (May/June) - world-famous ultramarathon\n• Midmar Mile (February) - world's largest open water swim\n\n**FOOD & WINE** 🍷\n• Durban Food Festival (seasonal)\n• Midlands Meander events\n• Night markets\n• Restaurant weeks\n\n**FAMILY EVENTS** 🎪\n• Circus performances\n• Kids festivals\n• Christmas markets\n• Outdoor cinemas (summer)\n\n**HOW I CAN HELP:**\n✅ Find events for your travel dates\n✅ Book tickets in advance (often sell out!)\n✅ Arrange transport to/from venue\n✅ Recommend accommodation near events\n✅ Create complete event + stay packages\n\nWhat kind of events interest you? When are you visiting? I'll check what's happening and get you sorted!";
  }

  // Family / kids - caring and practical
  if (/family|kids|children|baby|toddler|child/i.test(userMessage)) {
    return "Family travel is so precious - creating memories together! 👨‍👩‍👧‍👦 Let me help you plan something wonderful:\n\n**BEST FAMILY DESTINATIONS:**\n\n🏖️ **Ballito/Umhlanga**\n• Safe, Blue Flag beaches\n• Tidal pools perfect for little ones\n• Kid-friendly restaurants everywhere\n• Family resorts with kids clubs\n\n🦈 **uShaka Marine World (Durban)**\n• Aquarium with shark cage diving\n• Water park (slides, wave pool)\n• Beach right there\n• Restaurants with kids menus\n• Full day of fun: R195 adult, R145 child\n\n🐊 **Wildlife Experiences**\n• Croc World (Scottburgh) - safe, educational\n• PheZulu Safari Park - cultural village + crocs\n• Hluhluwe Game Reserve - Big 5 (malaria-free!)\n• Tala Private Game Reserve - great for first safari\n\n🎢 **Midlands Meander**\n• Farm activities (milk cows, feed animals)\n• Karkloof Canopy Tours (age 7+)\n• Picnics and nature walks\n• Pet lambs and ducks\n\n**AGE-APPROPRIATE ADVICE:**\n\n**Babies/Toddlers (0-3)**\n✅ Self-catering accommodation (flexibility)\n✅ Beach holidays (sand play, pool time)\n✅ Short travel distances\n❌ Avoid: Long game drives, hiking\n\n**Young Kids (4-8)**\n✅ uShaka, animal farms, easy nature trails\n✅ Beach + one safari (shorter drives)\n✅ Cultural villages (interactive)\n\n**Tweens/Teens (9-17)**\n✅ Adventure activities (ziplining, abseiling)\n✅ Full safari experience\n✅ Water sports (surfing, snorkeling)\n✅ Cultural immersion\n\n**PRACTICAL FAMILY TIPS:**\n🍼 All good hotels provide cots/high chairs (request ahead)\n👶 Baby supplies readily available in all cities\n🏥 Excellent medical facilities if needed\n🚗 Car seats can be arranged with rental\n💰 Most attractions offer family rates (2 adults + 2-3 kids)\n\n**HONEST PRICING** (family of 4):\n• Budget weekend: R8,000-12,000 total\n• Comfortable week: R25,000-45,000 total\n• Safari experience: R40,000-80,000 total\n\nHow old are your children? Any special needs or interests? I'll create the perfect family adventure!";
  }

  // Romantic / couples - Ubuntu touch
  if (/romantic|honeymoon|anniversary|couple|valentine|proposal|date|special occasion/i.test(userMessage)) {
    return "Love is beautiful, and you deserve something unforgettable! 💕 Let me help you create magic:\n\n**ULTRA-ROMANTIC SPOTS:**\n\n🌅 **Oyster Box Hotel (Umhlanga)**\n• Lighthouse views, colonial elegance\n• Spectacular service (Ubuntu hospitality)\n• Private beach access\n• Spa for couples\n• High tea tradition\n• R4,500-8,000/night\n\n🌴 **Mozambique Beach Escapes**\n• Pristine white sand, turquoise water\n• Luxury beach villas with private pools\n• Barefoot sophistication\n• Snorkeling coral reefs together\n• Sunset dhow cruises\n\n⛰️ **Drakensberg Romance**\n• Cathedral Peak Hotel - mountain views from bed\n• Cleopatra Mountain Farmhouse - intimate, gourmet\n• Fireplaces, spa treatments, wine\n• Sunrise hikes together\n• Complete privacy\n\n🍷 **Midlands Hideaways**\n• Boutique country hotels\n• Farm-to-table dining\n• Wine tasting experiences\n• Couple's spa journeys\n• Cozy winter escapes\n\n**SPECIAL EXPERIENCES I CAN ARRANGE:**\n\n💍 **Proposals**\n• Sunset beach setup (blanket, champagne, roses)\n• Private dinner under the stars\n• Helicopter ride over coastline\n• I'll coordinate with photographers!\n\n🥂 **Anniversaries**\n• Surprise room decorations\n• Private chef experiences\n• Couples massage bookings\n• Special dietary arrangements\n\n❤️ **Honeymoons**\n• Multi-destination packages\n• Upgrade surprises\n• Privacy guaranteed\n• Romance every detail\n\n**ROMANTIC INCLUSIONS I RECOMMEND:**\n✨ Couples spa treatments (R1,800-3,500)\n🍾 Private beach picnics with champagne\n🛥️ Sunset catamaran cruises\n🍽️ Private dining (on beach, in garden, on deck)\n💐 Room decoration with flowers and candles\n\n**HONEST BUDGETS** (3-4 nights for 2):\n• Beautiful: R15,000-25,000 total\n• Luxurious: R30,000-50,000 total  \n• Once-in-a-lifetime: R60,000+ total\n\nWhat's the occasion? Your style - quiet and intimate or adventurous romance? Budget comfort zone? I'll create something that feels like it was made just for you two. 💑";
  }

  // Safety & travel tips - Ubuntu caring
  if (/safe|safety|secure|dangerous|crime|worry|scared|tip|advice/i.test(userMessage)) {
    return "Your safety is my responsibility - I take this seriously. 🛡️ Let me share honest, practical guidance:\n\n**TRANSPORT SAFETY (most important!)**\n✅ **Use our vetted transfer services** - all drivers background-checked, rated, tracked\n❌ **Never hail taxis on the street** - this is where most problems happen\n✅ **Uber/Bolt are safe** in Durban, Umhlanga, Ballito during daytime\n🚗 **Night travel** - use our pre-booked drivers who know you&apos;re coming\n\n**ACCOMMODATION SAFETY**\n✅ I only recommend places in safe areas\n✅ All have secure parking if you&apos;re driving\n✅ 24-hour security/reception\n✅ Good lighting, proper access control\n🏨 **Umhlanga, Ballito, Durban beachfront** - very safe tourist areas\n\n**MONEY & VALUABLES**\n💳 Use cards where possible (widely accepted)\n💰 Carry minimal cash (R500-1000 for tips/markets)\n📱 Keep phone secure - don&apos;t walk distracted\n💎 Use hotel safes for passports/jewelry\n🎒 Keep bags close in busy areas\n\n**BEACH SAFETY**\n🏊 **Swim only at lifeguarded beaches**\n🚩 Respect the flags (red = dangerous)\n☀️ UV is strong - sunscreen essential!\n🌊 Rip currents exist - swim parallel to shore if caught\n\n**AREAS TO ENJOY vs AVOID**\n\n✅ **SAFE & RECOMMENDED:**\n• Umhlanga (day & night)\n• Ballito (day & night)\n• Durban beachfront promenade (day, evening groups)\n• Gateway Mall area\n• St Lucia village\n• Drakensberg resorts\n\n⚠️ **CAUTION/AVOID:**\n• Durban CBD at night (use transport)\n• Walking alone after dark anywhere\n• Deserted beaches\n• Displaying wealth\n\n**HEALTH & MEDICAL**\n🏥 Excellent private hospitals (Netcare, Life Healthcare)\n💊 Pharmacies everywhere (Clicks, Dis-Chem)\n🦟 KZN is LOW malaria risk (only far north in summer)\n💉 No special vaccines required for SA\n☎️ Emergency: 10177 or 112 from mobile\n\n**MY PERSONAL TIPS:**\n📱 Save my contact - 24/7 support if you need anything\n🗺️ I&apos;ll share safe walking routes for your specific hotel\n👥 Join groups for evening activities\n🚗 Keep car doors locked, windows up in traffic\n☀️ Travel during daylight when possible\n\n**HONEST TRUTH:**\n• Tourist areas are genuinely safe with basic precautions\n• Millions of tourists visit safely every year\n• Problems happen when people ignore advice\n• Ubuntu means community looks after visitors - we want you safe and happy!\n\nWhere will you be staying? I&apos;ll give you specific local advice for that area. And remember - I&apos;m always here if something feels wrong. 💚";
  }

  // Voice feature hint - encouraging
  if (/voice|speak|talk|microphone|mic|listen/i.test(userMessage)) {
    return "Yes, I can hear you! 🎤 This makes everything so easy:\n\n**JUST CLICK THE MICROPHONE** (top right of my panel, next to the close button)\n\nThen speak naturally, like:\n• &apos;Hi Zola, I need a shuttle from King Shaka to Ballito tomorrow at 2pm&apos;\n• &apos;Find me a beach hotel in Umhlanga for next weekend, 2 guests, budget R2000 per night&apos;\n• &apos;What&apos;s the weather like in Drakensberg in July?&apos;\n\nI understand:\n✅ Natural conversation (no robot speak needed!)\n✅ isiZulu greetings too (Sawubona, Yebo)\n✅ Locations, dates, times, numbers\n✅ Follow-up questions\n\nThe microphone turns **orange** when I&apos;m ready, **red and pulsing** when I&apos;m listening.\n\nTry it now - it&apos;s much faster than typing! 😊";
  }

  // Thank you / appreciation - Ubuntu response
  if (/thank|thanks|appreciate|grateful|helpful|great|awesome|perfect|love (it|this|you)|you're (the best|amazing|great)/i.test(userMessage)) {
    const responses = [
      "Ah, you warm my heart! 🤗 Ubuntu teaches us we rise together - your happiness is my happiness. What else can I do for you?",
      "It&apos;s truly my pleasure! Helping you succeed in your journey brings me joy. Is there anything else you need?",
      "Thank you for trusting me! 💚 This is what Ubuntu is about - we take care of each other. What&apos;s next on your list?",
      "You&apos;re so welcome, my friend! Your kind words mean everything. How else can I serve you today?",
    ];
    return responses[Math.floor(Math.random() * responses.length)];
  }

  // Durban specific - local expert
  if (/durban|dbn|ethekwini/i.test(userMessage) && !/transfer|shuttle|airport/i.test(userMessage)) {
    return "Durban - eThekwini - my home! 🌴 Let me share what makes this city special:\n\n**MUST-EXPERIENCE** (honestly!)\n\n🏖️ **Golden Mile Promenade**\n• 6km beachfront walkway\n• Safe for jogging, walking, cycling (day & early evening)\n• Beach vendors, Afro-Caribbean vibe\n• People watching is world-class!\n\n🏛️ **Moses Mabhida Stadium**\n• Take the SkyCar (R95) for 360° views\n• Big Swing (110m arc!) for adrenaline\n• Segway tours around Durban\n• Walk/run up the arch steps (500+ steps!)\n\n🦈 **uShaka Marine World**\n• World-class aquarium (R195 adult)\n• Water park attached\n• Shark diving experience\n• Restaurants right on the beach\n\n🍛 **Indian Heritage**\n• Victoria Street Market (spices, fabrics, curry)\n• Bunny chow (Durban's iconic dish - hollowed bread loaf filled with curry)\n• Best bunny chow: Goundens, House of Curries, Britannia Hotel\n• Juma Masjid Mosque (magnificent architecture)\n\n🌺 **Durban Botanic Gardens**\n• Africa's oldest surviving botanical gardens (1849)\n• Orchid House, cycad collection\n• Free entry! Perfect for picnics\n• Sunday markets sometimes\n\n🎭 **Florida Road**\n• Restaurant hub (30+ eateries)\n• Nightlife, live music\n• Safe area with good parking\n• Vibe is diverse and energetic\n\n**DAY TRIPS FROM DURBAN:**\n• Valley of 1000 Hills (45 min) - craft markets, viewpoints\n• Umhlanga (20 min) - upscale beach, shopping\n• Ballito (45 min) - dolphin coast, tidal pools\n• Shakaland (2 hours) - Zulu cultural village\n\n**HONEST INSIDER TIPS:**\n✅ Best beaches: North Beach, Bay of Plenty (lifeguards)\n✅ Parking: Use secure parking (R20-40), don't street park valuables\n✅ Weather: Humid! Dress light, sunscreen essential\n🌧️ Summer rain: Usually afternoon storms, passes quickly\n🍽️ Food: Indian, Zulu, Portuguese - incredible diversity\n\n**AREAS FOR VISITORS:**\n🏨 **Where to stay:**\n• Umhlanga (safe, upscale, beach)\n• Durban North Beach area (beachfront)\n• Ballito (quieter, family-friendly)\n\n⚠️ **CBD at night** - use transport, don't walk\n✅ **Daytime CBD** - markets, shopping (watch belongings)\n\nWhat specifically about Durban interests you? I'll dig deeper into that!";
  }

  // Complaints / problems - Ubuntu problem-solving
  if (/problem|issue|complaint|wrong|bad|terrible|awful|disappointed|unhappy|cancel/i.test(userMessage)) {
    return "I'm truly sorry something's not right. 😔 Please tell me exactly what's wrong - I'm here to fix this, not defend it.\n\nUbuntu teaches us: when one person has a problem, we all have a problem. Your issue is MY issue now.\n\nWhat happened? I'm listening, and I'll make this right. 💚";
  }

  // Accessibility / special needs - caring and thorough
  if (/wheelchair|disabled|disability|accessible|accessibility|special needs|mobility/i.test(userMessage)) {
    return "Accessibility matters deeply - everyone deserves to travel! ♿ Let me help you properly:\n\n**WHEELCHAIR ACCESSIBLE VENUES:**\n✅ Moses Mabhida Stadium - excellent access\n✅ uShaka Marine World - mostly accessible\n✅ Gateway Theatre of Shopping - fully accessible\n✅ Most modern hotels (I&apos;ll verify for you)\n✅ Umhlanga promenade - wheelchair friendly\n\n**TRANSPORT:**\n🚗 We have wheelchair-accessible vehicles\n🚕 Must be pre-booked (not all drivers equipped)\n✈️ King Shaka Airport - good accessibility\n\n**SAFARI ACCESSIBILITY:**\n🦁 Yes, it&apos;s possible!\n• Some lodges have accessible rooms & vehicles  \n• Shorter game drives can be arranged\n• Let me find the right place for your needs\n\n**BEACHES:**\n🏖️ Some beaches have beach wheelchairs available\n🏖️ Durban beachfront promenade is accessible\n\n**WHAT I NEED TO HELP YOU BEST:**\n• Mobility level (full wheelchair, limited walking, etc.)\n• Any other requirements (dietary, medical)\n• Traveling companions\n• Budget and preferences\n\nI&apos;ll personally verify accessibility with each provider before confirming anything. Your comfort and dignity are non-negotiable. 💚\n\nTell me your specific needs?";
  }

  // Fallback - encouraging, warm, Ubuntu spirit
  const fallbacks = [
    "I&apos;m here to help you, truly. Could you share a bit more about what you&apos;re looking for? Your destination, budget, or the kind of experience that would make you happy?",
    "Let&apos;s figure this out together! Tell me: Where would you love to go? When? What matters most to you - adventure, relaxation, culture, budget?",
    "I&apos;m listening. 💚 What&apos;s on your mind? Whether it&apos;s a dream trip, a practical question, or just exploring ideas - I&apos;m here for you.",
    "Help me understand what you need, my friend. Sometimes the best trips start with a simple conversation. What&apos;s drawing your interest right now?",
  ];
  
  return fallbacks[Math.floor(Math.random() * fallbacks.length)];
}
