import fs from 'fs'
import path from 'path'

function findPdfBundle() {
  const assetsDir = path.resolve(process.cwd(), 'dist', 'assets')
  if (!fs.existsSync(assetsDir)) return null
  const files = fs.readdirSync(assetsDir)
  return files.find(f => f.startsWith('pdfGenerators') && f.endsWith('.js')) || null
}

async function normalizeToBuffer(result) {
  if (!result) return null
  if (typeof result === 'string') {
    const m = result.match(/^data:application\/pdf(;[^,]+)?,(.*)$/)
    if (m) {
      const b64 = m[2]
      return Buffer.from(b64, 'base64')
    }
    // maybe plain base64
    if (/^[A-Za-z0-9+/=\r\n]+$/.test(result.replace(/\s+/g, ''))) {
      return Buffer.from(result.replace(/\s+/g, ''), 'base64')
    }
    return null
  }
  if (result instanceof ArrayBuffer) return Buffer.from(new Uint8Array(result))
  if (ArrayBuffer.isView(result)) return Buffer.from(result.buffer, result.byteOffset, result.byteLength)
  if (Buffer.isBuffer(result)) return result
  return null
}

async function run() {
  const bundle = findPdfBundle()
  if (!bundle) {
    console.error('Could not find pdfGenerators bundle in dist/assets. Run `npm run build` first.')
    process.exit(1)
  }

  const distFile = path.resolve(process.cwd(), 'dist', 'assets', bundle)
  console.log('Found bundle:', distFile)

  const mod = await import('file://' + distFile.replace(/\\/g, '/'))
  // try common export names and fallbacks
  let exporter = mod.exportQuotePdfData || mod.generateQuotePdf || mod.exportQuote || null
  if (!exporter && mod.default) exporter = mod.default.exportQuotePdfData || mod.default.generateQuotePdf || mod.default.exportQuote || null

  if (!exporter) {
    // try to find any function export
    for (const k of Object.keys(mod)) {
      if (typeof mod[k] === 'function') { exporter = mod[k]; break }
    }
  }

  if (!exporter) {
    console.error('No exporter function found in module. Available keys:', Object.keys(mod))
    process.exit(1)
  }

  const sample = {
    clientName: 'Sample Client',
    clientEmail: 'sample@example.com',
    clientPhone: '+27123456789',
    currency: 'USD',
    taxRate: 0,
    notes: 'Generated by scripts/generate_sample_quote.mjs',
    paymentTerms: 'Due on receipt',
    items: [
      { title: 'Room (Sea view)', description: 'Twin room', quantity: 2, unitPrice: 120 },
      { title: 'Transfer', description: 'Airport return transfer', quantity: 1, unitPrice: 40 }
    ]
  }

  console.log('Calling exporter...')
  const result = await exporter(sample)
  const buf = await normalizeToBuffer(result)
  if (!buf) {
    console.error('Exporter returned unexpected result type. Got:', typeof result)
    process.exit(1)
  }

  const out = path.resolve(process.cwd(), 'tmp', 'sample-quote.pdf')
  fs.mkdirSync(path.dirname(out), { recursive: true })
  fs.writeFileSync(out, buf)
  console.log('Wrote PDF to', out, 'size', buf.length)
}

run().catch(err => { console.error(err); process.exit(1) })
