<#
PowerShell helper to untrack committed runtime artifacts and create a commit that adds .gitignore entries.

Usage (run locally from repo root):
  pwsh.exe -File scripts/untrack-artifacts.ps1

What it does:
 - Shows the list of files under ./artifacts that are currently tracked
 - Runs: git rm -r --cached --quiet artifacts || true
 - Commits the removal and updated .gitignore if there are staged changes
 - Prints instructions to push the branch or open a PR

This script does NOT force-push or rewrite history. If you need to purge large files from history use BFG/git filter-repo (coordination required).
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Ensure we're in repo root
$repoRoot = (Get-Location).Path
if (-not (Test-Path (Join-Path $repoRoot ".git"))) {
    Write-Error "This directory does not appear to be a git repository. Run this script from the repository root."
    exit 1
}

Write-Host "Repository root: $repoRoot"

if (-not (Test-Path "$repoRoot\artifacts")) {
    Write-Host "No artifacts/ directory found — nothing to untrack."
    exit 0
}

Write-Host "Files currently under artifacts/ (tracked and untracked):"
Get-ChildItem -Path "$repoRoot\artifacts" -Recurse | Select-Object FullName, Length | %{ Write-Host $_.FullName }

Write-Host "\nPreparing to remove artifacts/ from git index (git rm --cached -r artifacts)"

# Show what would be removed
Write-Host "Staged candidate removals (dry-run):"
& git ls-files -- "artifacts/**" | ForEach-Object { Write-Host "  $_" }

Read-Host "Press Enter to continue and run: git rm -r --cached artifacts (or Ctrl-C to abort)"

# Attempt to remove from index
try {
    & git rm -r --cached artifacts | Out-Null
} catch {
    Write-Warning "git rm returned non-zero or no tracked files found. Continuing."
}

# Ensure .gitignore is present and contains the artifacts entry
$gitignorePath = Join-Path $repoRoot ".gitignore"
if (-not (Test-Path $gitignorePath)) {
    Write-Host "No .gitignore found — creating one.";
    "# Generated by scripts/untrack-artifacts.ps1" | Out-File -FilePath $gitignorePath -Encoding utf8
}

# Show staged changes
Write-Host "\nStaged changes summary:"
& git status --porcelain

# Commit if there are staged changes
$changes = (& git status --porcelain)
if ($changes) {
    Write-Host "Committing removal and .gitignore changes..."
    & git add .gitignore
    & git commit -m "chore: remove runtime CI artifacts from repository and ignore them (artifacts/)"
    Write-Host "Committed. Review and push or open a PR as appropriate."
} else {
    Write-Host "No staged changes detected — nothing to commit."
}

Write-Host "Done. To push the current branch to origin run: git push origin HEAD"
Write-Host "If you need to completely purge large files from history, coordinate first and use 'git filter-repo' or 'bfg', then force-push."
