import fs from 'fs'
import path from 'path'
import nodemailer from 'nodemailer'

const assetsDir = path.resolve('./dist/assets')

function findBundle() {
  if (!fs.existsSync(assetsDir)) return null
  const files = fs.readdirSync(assetsDir)
  const f = files.find(f => f.startsWith('pdfGenerators') && f.endsWith('.js'))
  return f ? path.join(assetsDir, f) : null
}

async function run() {
  const bundle = findBundle()
  if (!bundle) {
    console.error('Could not find pdfGenerators bundle in dist/assets — run npm run build first')
    process.exit(1)
  }

  console.log('Importing bundle:', bundle)
  const mod = await import('file://' + bundle.replace(/\\/g, '/'))
  const exporter = mod.exportQuotePdfData || mod.generateQuotePdf || mod.default?.exportQuotePdfData || mod.default?.generateQuotePdf
  if (!exporter) {
    console.error('No exporter found. Available keys:', Object.keys(mod))
    process.exit(1)
  }

  const sample = {
    clientName: 'Preview Tester',
    clientEmail: 'preview@example.com',
    clientPhone: '+27123456789',
    currency: 'USD',
    taxRate: 0,
    notes: 'Generated by verify_send_auto for preview',
    paymentTerms: '50% upfront',
    items: [
      { title: 'Room', description: 'Sea view', quantity: 2, unitPrice: 120 },
      { title: 'Transfer', description: 'Return', quantity: 1, unitPrice: 40 }
    ]
  }

  console.log('Calling exporter...')
  const dataUri = await exporter(sample)
  if (!dataUri || typeof dataUri !== 'string') {
    console.error('Exporter returned unexpected result:', dataUri)
    process.exit(1)
  }

  const m = dataUri.match(/^data:application\/pdf;base64,(.+)$/)
  if (!m) {
    console.error('Unexpected dataUri format')
    process.exit(1)
  }
  const b64 = m[1]
  const buf = Buffer.from(b64, 'base64')
  const outPath = path.resolve('./tmp/preview-quote.pdf')
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, buf)
  console.log('Wrote PDF to', outPath, 'size', buf.length)

  // optional: create nodemailer preview URL
  try {
    const testAccount = await nodemailer.createTestAccount()
    const transporter = nodemailer.createTransport({
      host: testAccount.smtp.host,
      port: testAccount.smtp.port,
      secure: testAccount.smtp.secure,
      auth: { user: testAccount.user, pass: testAccount.pass }
    })
    const info = await transporter.sendMail({
      from: 'no-reply@example.com', to: 'you@example.com', subject: 'Preview Quote', text: 'Preview attached', attachments: [{ filename: 'preview-quote.pdf', content: buf }]
    })
    console.log('Nodemailer preview URL:', nodemailer.getTestMessageUrl(info))
  } catch (e) {
    // not fatal
  }
}

run().catch(err => { console.error(err); process.exit(1) })
