name: Mobile Viewport E2E

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-mobile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spec:
          - cypress/e2e/mobile-home.cy.js
          - cypress/e2e/mobile-itinerary.cy.js
          - cypress/e2e/mobile-packages.cy.js
          - cypress/e2e/mobile-bookings.cy.js
          - cypress/e2e/mobile-quotes.cy.js
          - cypress/e2e/mobile-contact.cy.js
          - cypress/e2e/mobile-about.cy.js
          - cypress/e2e/mobile-partners.cy.js
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore Cypress cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build and start stack
        run: |
          npm run smoke:build
          npx start-server-and-test "npm run smoke:start:stack" http://localhost:4010/health "echo Stack ready"

      - name: Run spec ${{ matrix.spec }}
        run: |
          npx cypress run --browser chrome --e2e --spec ${{ matrix.spec }} --config video=true,screenshotsFolder=cypress/screenshots,videoCompression=32
        env:
          CI: true

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.spec }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.spec }}
          path: cypress/videos
          if-no-files-found: ignore
