name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup CNAME
        run: echo "travelcolleco.com" > dist/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: 'github-actions'
          user_email: 'actions@users.noreply.github.com'
