name: Notify PR on E2E failure

on:
  workflow_run:
    workflows: ["E2E PR Smoke"]
    types: [completed]

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post PR comment suggesting diagnostic run
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = context.payload.workflow_run;
            const prs = run.pull_requests || [];
            if (!prs.length) {
              core.info('No associated PRs found for the failing workflow run.');
              return;
            }
            const body = `The **E2E PR Smoke** workflow just failed. If you need detailed diagnostics, add the label **e2e-diag** to this PR (or request a diagnostic run) to trigger an on-demand E2E run that collects screenshots and logs.`;
            for (const pr of prs) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body,
              });
            }