name: PR Merge Checklist Comment

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post checklist comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🧭 Merge Checklist
            - [ ] CI (lint/tests/build) green
            - [ ] E2E Smoke green
            - [ ] GitHub Pages deploy configured (hash routing/base path)
            - [ ] Backend env set in prod: `NODE_ENV=production`, `API_TOKEN`, `ALLOWED_ORIGINS`
            - [ ] CORS preflight passes; `/health` reachable
            - [ ] PWA manifest served at `/manifest.webmanifest`
