name: Prune triage (test data run)

on:
  workflow_dispatch:

jobs:
  create-and-prune:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test triage directories with old timestamps and files
        run: |
          set -e
          echo "Creating artifacts/triage/run-old and run-new with marker files"
          mkdir -p artifacts/triage/run-old
          mkdir -p artifacts/triage/run-new
          echo "old" > artifacts/triage/run-old/marker.txt
          echo "new" > artifacts/triage/run-new/marker.txt
          # make run-old appear 40 days old, run-new 10 days old
          touch -d "40 days ago" artifacts/triage/run-old
          touch -d "10 days ago" artifacts/triage/run-new
          ls -la artifacts/triage || true
          stat -c '%n %Y' artifacts/triage/run-old || true

      - name: Run prune (force deletion for test)
        run: |
          # Pass the PowerShell literal $false (single-quoted) so bash doesn't expand it
          pwsh -NoProfile -ExecutionPolicy Bypass ./scripts/prune-triage.ps1 -Days 30 '-DryRun:$false'

      - name: Upload prune results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prune-triage-testdata-${{ github.run_id }}
          path: |
            artifacts/triage/**

      - name: Output note
        run: |
          echo "Created test triage dirs and ran prune. Check uploaded artifact prune-triage-testdata-${{ github.run_id }}"
